### ISSUE TITLE
Request for your group's code

### ISSUE THREAD

**Issue by Wakaka161** [JinshuaiBai/RPIM_NNS#1]
My name is Wang Yueyang, a doctoral student at the School of Mathematical Sciences, Peking University, specializing in Computational Mathematics. I recently had the pleasure of reading your group's excellent paper titled "**A complete Physics-Informed Neural Network-based framework for structural topology optimization**".

It appears that you and the first author, Hyogu Jeong, are in the same research group. However, I have been unable to find Hyogu Jeong's email address and thus am reaching out to you directly.

If it is convenient, could you assist me in obtaining the code from the first author? I would greatly appreciate your help. My email address is 'wangyueyang@pku.stu.edu.cn'.

Thank you very much for your time and consideration. I look forward to your response.

**Comment by JinshuaiBai** [comment]
> My name is Wang Yueyang, a doctoral student at the School of Mathematical Sciences, Peking University, specializing in Computational Mathematics. I recently had the pleasure of reading your group's excellent paper titled "**A complete Physics-Informed Neural Network-based framework for structural topology optimization**".
> 
> It appears that you and the first author, Hyogu Jeong, are in the same research group. However, I have been unable to find Hyogu Jeong's email address and thus am reaching out to you directly.
> 
> If it is convenient, could you assist me in obtaining the code from the first author? I would greatly appreciate your help. My email address is '[wangyueyang@pku.stu.edu.cn](mailto:wangyueyang@pku.stu.edu.cn)'.
> 
> Thank you very much for your time and consideration. I look forward to your response.

It seems that your email address is wrong.
Could you please send me an email via your address?

**Comment by Wakaka161** [comment]
Sorry, I don't know your email, but I did write my email wrong. My correct email address is 'wangyueyang@stu.pku.edu.cn'. I apologize for any inconvenience this may have caused.
